version: '3.8'

services:
  master:
    image: postgres:17
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  replica:
    image: postgres:17
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_replica_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_master_data:
  pg_replica_data:
